// Single source of truth for the Work OS team-setup documentation.
// Rendered by build.js to: the multi-page HTML site, one Markdown file (repo), one DOCX per platform.
// Inline markup: **bold**, *italic*, `code`, [text](url), {gh:GitHub wording|az:Azure wording}.
const h2 = (text, id) => ({ t: "h2", text, id });
const h3 = (text, id) => ({ t: "h3", text, id });
const p = (text) => ({ t: "p", text });
const lead = (text) => ({ t: "lead", text });
const steps = (items) => ({ t: "steps", items: items.map((i) => (typeof i === "string" ? { text: i, sub: [] } : i)) });
const step = (text, ...sub) => ({ text, sub });
const bullets = (items) => ({ t: "bullets", items });
const checklist = (items) => ({ t: "checklist", items });
const code = (lines, label) => ({ t: "code", lines: Array.isArray(lines) ? lines : [lines], label });
const say = (text) => ({ t: "say", text });                     // a prompt to type into Claude Code — copyable
const callout = (kind, text) => ({ t: "callout", kind, text }); // expected | check | note | why | dont | pass | tip
const table = (header, rows, widths) => ({ t: "table", header, rows, widths });
const terms = (items) => ({ t: "terms", items });
const platform = (name, ...blocks) => ({ t: "platform", name, blocks }); // "github" | "azure"
const details = (summary, ...blocks) => ({ t: "details", summary, blocks });
const image = (file, alt, caption) => ({ t: "image", file, alt, caption });   // file in the build folder; HTML/DOCX embed it, MD shows the alt text
const seq = (items) => ({ t: "seq", items });                    // the big-picture sequence: [{who, what, time, link}]
const cards = (items) => ({ t: "cards", items });                // [{title, text, link}]

const SRC = "https://github.com/alexey-orlov/SoftServe-Work-OS";
const ADO_FILTER = "/product-development/feature-index.yaml;/product-development/product/strategy/business-context/*;/product-development/product/handbook/templates/*;/product-development/engineering/*;/CLAUDE.md;/governance/*;/os-installation/*;/Documentation/*;/.claude/*;/.github/*";

const doc = {
  name: "Work OS Team Setup",
  siteTitle: "Work OS · Team setup",
  version: "v2.4 · August 2026",
  repoPath: "Documentation/",
  intro: "How to set up and customize the Work OS for your organization — who does what, how the repository is set up on {gh:GitHub|az:Azure Repos}, how each person gets going, how the Work OS is customized and connected to your tools and code, and how changes flow. Also published as an interactive site with a GitHub / Azure Repos switch, and as a Word document per platform.",
  home: ["overview", "work-os-101"],
  sections: [
    // ================================================================= OVERVIEW
    { id: "overview", title: "Overview", articles: [

      { id: "work-os-101", title: "Work OS 101", audience: "Everyone", time: "8 min read", blocks: [
        lead("The Work OS is a shared operating system for product work with Claude: a governed repository of **context** (what the team knows), **skills** (how the team works) and **rules** (what may change, and how) that Claude reads, uses and keeps up to date. It turns Claude from a chat window into a team asset — one that compounds as people use it."),
        h2("Three terms you'll hear", "terms"),
        table(["", "What it is", "One line"], [
          ["**LLM** — answers", "A model that answers one prompt at a time: it reads what you give it and writes back. No memory, no tools, no initiative.", "Claude Chat, ChatGPT"],
          ["**Agent** — acts", "An LLM in a loop with tools: it plans, takes multi-step actions (reads files, searches, writes), checks results and iterates until the job is done.", "Claude Code"],
          ["**Agent OS** — compounds", "An agent working inside a dynamic, maintained operating system: a governed repository of skills and a context system it reads, uses and keeps up to date.", "Claude Code + the Work OS repository — this is the Work OS"],
        ], [2000, 5000, 2400]),
        h2("What it is for", "purpose"),
        p("Product work runs on context — who the customer is, what was decided, what the numbers say, what the team agreed a good PRD looks like. Without a Work OS, that context lives in people's heads and private chats, so every AI answer starts from zero and every PM re-teaches their own assistant. The Work OS puts that context in one shared, versioned place and gives every teammate's Claude the same skills, so:"),
        bullets([
          "**Answers are grounded** — Claude reads your business context, strategy and decisions before it drafts, and cites them.",
          "**Best practice is shared** — the team's way of writing a PRD, running a meeting or sizing a feature is one skill everyone runs, and improving it once improves everyone's next result.",
          "**The system learns** — corrections become rules; what one person fixes, nobody has to fix again.",
          "**It stays safe** — access rules, a write policy and review flows keep a shared system auditable and trusted.",
        ]),
        h2("What it comprises — six capabilities", "capabilities"),
        image("pillars.jpg", "Key pillars — six capabilities that separate a Work OS from a chat window", "The six pillars, from the AI PM Jumpstart programme."),
        table(["Capability", "What it means", "In the Work OS"], [
          ["Reasoning and multi-step execution", "The agent doesn't just answer: it plans, runs multi-step work (research, draft, check) and asks when unsure.", "Run `/process-meeting` on a transcript: the summary is filed, decisions routed to the decision log, linked pages updated — you review the result."],
          ["Skills", "Named, reusable workflows invoked by you or by other skills — the team's best practice runs the same way every time.", "`/prd-draft` is one shared skill, versioned in the repository. Anyone runs it; improve it once and everyone's next PRD is better. See [Skills and agents](#/overview/skills)."],
          ["Context", "What the agent knows before you ask: business info, strategy, customers, decisions — shared, current, in one repository.", "Claude reads `business-info.md`, `segmentation-matrix.md` and `current-quarter.md` first; drafts cite your ICP, your segments and this quarter's bets. See [Context system](#/overview/context)."],
          ["Self-improvement", "Corrections become rules: the OS learns from use, so the same mistake isn't corrected twice.", "Correct something once — it becomes a rule in `team-learnings.md`, and every session for every PM starts already knowing it."],
          ["Workflow integration", "Agents act in your real systems — repository, docs, tickets, analytics — through connectors (MCP) and triggers.", "`/weekly-review` assembles the digest from the repository — and, once tools are connected, from your analytics and chat — and posts it where the team reads. See [Connect your tools](#/setup/tools)."],
          ["Governance", "Access rules, write policies and review flows, so a shared OS stays safe, auditable and trusted.", "Everyday files flow freely; gated files change only with an explicit yes and an admin's approval; every change is a reviewable, revertible diff. See [How changes reach the team](#/overview/changes)."],
        ], [2200, 3600, 3600]),
        h2("The underlying technology", "technology"),
        p("Nothing exotic — three well-understood parts, each replaceable:"),
        bullets([
          "**Claude Code** — Anthropic's agent. It runs on your computer (the desktop app), reads and writes files in the Work OS folder, runs skills, and talks to your tools through MCP connectors.",
          "**A git repository** — plain Markdown and YAML files in folders, versioned in {gh:GitHub|az:Azure Repos}. Git is how developers have shared and versioned work for years; here it carries the team's knowledge instead of code — audited, updated and versioned by default, tool-agnostic.",
          "**Auto-sync and the write policy** — a small set of scripts and one policy file inside the repository. They save your work automatically, move everyday changes to the shared branch, and route changes to gated files through an approval. See [How changes reach the team](#/overview/changes).",
        ]),
        h2("Where it lives — the repository", "repository"),
        p("Everything is a file in one folder tree. The same tree is on every teammate's computer and in {gh:GitHub|az:Azure Repos}; the [Context system](#/overview/context) article walks through it item by item."),
        code([
          "work-os/",
          "├── CLAUDE.md                        master context + team roster — loaded every session",
          "├── .claude/",
          "│   ├── skills/                      the PM skills (slash commands)",
          "│   ├── agents/                      code explorer + reviewer personas",
          "│   └── team-learnings.md            corrections that became rules",
          "├── product-development/",
          "│   ├── feature-index.yaml           feature → artifacts map",
          "│   ├── inbox/                       transcript drop zone",
          "│   ├── product/",
          "│   │   ├── strategy/                business context · current quarter · roadmaps",
          "│   │   ├── customers/               accounts · feature requests · research syntheses",
          "│   │   ├── competitive-research/    landscape · matrix · teardowns",
          "│   │   ├── initiatives/  decisions/  meetings/",
          "│   │   ├── PRDs/{area}/             + examples/",
          "│   │   └── reports/  planning/  launches/  handbook/templates/",
          "│   ├── analytics/                   metrics · queries · dashboards · experiments",
          "│   └── engineering/                 code registry + grounding for /code-qa",
          "├── governance/                      write policy · health reports · proposals",
          "├── os-installation/                 install and setup guides",
          "└── Documentation/                   this documentation — site, Word editions, source",
        ], "The Work OS folder"),
        h2("How it stays in sync", "sync"),
        p("Three places, one loop: the shared repository in {gh:GitHub|az:Azure Repos} · Claude Code + git on your computer · your local files. Git carries files between the shared repository and your machine; Claude Code works on the local copy; auto-sync runs the loop for you after every response. You never hand-move files."),
        h2("Four levels of AI acceleration", "levels"),
        p("Most teams start at level 1 or 2. The Work OS is level 4 — a personal agent with a maintained context system, made team-wide, versioned and governed. What one person improves, everyone gets."),
        image("levels.jpg", "Levels of AI acceleration — chat, projects, personal agent + Work OS, team agent + Work OS", "Each level adds a capability the previous one lacks; the Work OS is level 4."),
        table(["", "Level 1 · Chat", "Level 2 · Projects", "Level 3 · Personal agent + Work OS", "Level 4 · Team agent + Work OS"], [
          ["What it is", "Direct interaction with the model", "Static context grouped by project", "Dynamic context system for a single user", "The team's shared context system"],
          ["Instant answers and drafting", "●", "●", "●", "●"],
          ["Static project context", "–", "●", "●", "●"],
          ["Dynamic context, agent-maintained", "–", "–", "●", "●"],
          ["Reusable skills and sub-agents", "–", "–", "●", "●"],
          ["Acts in your files and tools", "–", "partial", "●", "●"],
          ["Team-shared, versioned, governed", "–", "–", "–", "●"],
        ], [2400, 1500, 1600, 1900, 2000]),
        callout("tip", "New here? Read [Skills and agents](#/overview/skills) to see what Claude can do for you, then [Context system](#/overview/context) to see what it knows. When you're ready to roll it out, start with [Setup › Overview](#/setup/overview)."),
      ]},

      { id: "skills", title: "Skills and agents", audience: "Everyone", time: "6 min read", blocks: [
        lead("A **skill** is a named, reusable workflow: you type `/skill-name` (or just ask in plain words) and the team's agreed way of doing that piece of work runs — reading the right context first, writing the result to the right place. An **agent** is a specialist Claude spins up for part of a job: a reviewer with a fixed perspective, or a read-only code explorer. Skills live in `.claude/skills/`, agents in `.claude/agents/`; both are versioned with the repository, so improving one improves it for everyone."),
        callout("note", "Groups below mirror `.claude/skills/CLAUDE.md`, the skills index in the repository. Every skill also runs from a plain sentence — \"process this transcript\" runs `/process-meeting`."),
        h2("Communication & ops", "g-comm"),
        p("Meeting processing, decision logging, status updates and digests, personal planning."),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/process-meeting`", "One entry point for every meeting record — customer calls, interviews, internal meetings, retros", "A transcript (pasted, a file, or from a connected tool)", "Filed transcript + summary; decisions and lessons routed; account and initiative pages updated"],
          ["`/decision-doc`", "Deliberates a decision *before* it is made — options, tradeoffs, recommendation, sign-off routing", "The decision to make and what you know", "A decision document; files the record once decided"],
          ["`/decision-log-entry`", "Records a decision *after* it is made — reasoning, options, tradeoff, who was in the room", "What was decided, why, alternatives", "A dated entry in `product/decisions/`"],
          ["`/meeting-agenda`", "Creates a structured agenda", "Topic, attendees, duration, decisions needed", "A ready-to-send agenda"],
          ["`/meeting-feedback`", "Post-meeting effectiveness feedback", "Which meeting, did it achieve its goal", "A short feedback note with improvements"],
          ["`/status-update`", "Stakeholder status updates for a chosen audience", "Audience, period, what happened", "A concise update in the audience's language"],
          ["`/slack-message`", "Drafts team messages for chat", "Purpose, recipient, context", "A ready-to-paste message (or posted, when chat is connected)"],
          ["`/weekly-review`", "Closes the week — team digest by initiative + your own execution review", "Nothing — reads the repository (and connected tools)", "The week's digest in `product/reports/`, chat-ready"],
          ["`/weekly-plan`", "Sets next week's priorities against the quarter", "Your candidates for the week", "A prioritized weekly plan in `product/planning/`"],
          ["`/daily-plan`", "A compact daily plan with context", "Nothing required", "TL;DR, top 3, schedule, heads-up"],
          ["`/portfolio-pulse`", "Exec-grade synthesis across accounts and active features", "Nothing — reads accounts, initiatives, reports", "Health, risks, expansion signals, top 3 priorities, drafted messages"],
        ], [1800, 3200, 2200, 2600]),
        h2("Definition", "g-def"),
        p("Strategy, PRDs, metric definitions, impact sizing, experiment design — and the critique passes that stress-test them."),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/prd-draft`", "Drafts and iterates a PRD as the living spine of a feature; marks unbacked sections `[GAP:]` and runs bounded research to close them", "A feature idea, brief, or an existing initiative", "The PRD, the initiative page, a readiness readout"],
          ["`/prd-challenge`", "Every critique lens on the PRD at once, in parallel — assumption map, red team, reviewer personas, pre-mortem", "A PRD path", "One deduplicated challenge report led by ranked unverified assumptions"],
          ["`/jobs-breakdown`", "Cuts an agreed initiative into independently shippable jobs, riskiest assumption first", "An initiative or PRD", "The jobs breakdown — a live status board"],
          ["`/job-spec-draft`", "Writes the buildable contract for one job — between the PRD and tickets", "A job from a breakdown", "The job spec, with engineering confirmations listed"],
          ["`/job-spec-challenge`", "Independent judgment on a job spec — three-amigos panel, legal, designer, feasibility", "A job spec path", "A readiness-for-tickets report"],
          ["`/assumption-map`", "Surfaces every assumption a plan rests on and ranks them by impact and uncertainty", "An idea, draft or PRD", "A ranked assumption map"],
          ["`/red-team`", "Attacks the load-bearing claims of a PRD, strategy or decision", "The document", "A red-team report"],
          ["`/pre-mortem`", "Rehearses the failed launch and classifies risks (tigers / paper tigers / elephants)", "The feature or launch", "Owned, dated action plans for launch-blocking risks"],
          ["`/feature-metrics`", "Defines a feature's success metrics — primary, guardrails, kill criteria", "The feature and its goal", "Metric definitions in `analytics/metrics/`"],
          ["`/experiment-metrics`", "Validates experiment metrics with the STEDII checks", "The experiment and candidate metrics", "A vetted metric set"],
          ["`/experiment-decision`", "Decides A/B test vs. ship-and-monitor vs. just ship", "What you're considering, expected impact", "A clear recommendation with reasoning"],
          ["`/impact-sizing`", "Quantifies feature value by business lever, every factor sourced or marked as a gap", "The feature", "A sized impact estimate with confidence"],
          ["`/metrics-framework`", "Leading vs. lagging indicators for a product or feature", "The product/feature", "A metrics framework"],
          ["`/define-north-star`", "Identifies and validates the North Star metric", "Your strategy context", "A validated North Star with inputs"],
          ["`/expansion-strategy`", "Upsell, cross-sell and account-growth tactics", "Pricing tiers, expansion signals", "An expansion strategy"],
          ["`/strategy-sprint`", "Product strategy in 1 day / 1 week / 1 month", "The topic and timeframe", "A strategy document"],
          ["`/write-prod-strategy`", "Product strategy using the 7-component framework", "The product or initiative", "A strategy document"],
        ], [1800, 3400, 2200, 2400]),
        h2("Delivery", "g-del"),
        p("Turning a spec into tickets, code and a shipped launch — plus what the shipped code actually does, and triaging what comes back in."),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/create-tickets`", "Turns an agreed PRD or job spec into dev-backlog tickets, or pushes feature requests as intake tickets", "The spec (or the request records)", "Tickets in your tracker, or formatted text to paste"],
          ["`/code-qa`", "Answers product questions from the code itself — how it works today, limits, is it live", "A question", "A concise plain-language answer; evidence on request"],
          ["`/code-first-draft`", "First-pass implementation of a spec in your codebase", "A job spec or PRD", "Working code with tests, for engineers to take over"],
          ["`/pm-handoff`", "Readiness gate for handing requirements to BA / TPM / PO", "An initiative or job", "READY / NOT READY with a checklist"],
          ["`/launch-checklist`", "Prioritized, dependency-mapped launch plan sized to the launch", "What you're launching", "The checklist in `product/launches/`"],
          ["`/feature-results`", "Post-launch analysis and results", "Feature, hypothesis, actual results", "A results record"],
          ["`/prioritize-requests`", "Clusters inbound requests by the job behind them and routes each theme", "Call summaries or a pasted pile of requests", "One living prioritization file"],
        ], [1800, 3400, 2200, 2400]),
        h2("Discovery: market analysis", "g-market"),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/competitor-analysis`", "Deep competitive analysis or ongoing monitoring", "Competitor name(s) and the mode", "Updated landscape, matrix and teardowns"],
        ], [1800, 3400, 2200, 2400]),
        h2("Discovery: customers", "g-cust"),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/interview-guide`", "JTBD-based interview guides", "Topic and who you'll interview", "A ready interview guide"],
          ["`/user-research-synthesis`", "Turns interviews into actionable insights", "Interview notes or transcripts", "A synthesis report in `customers/research-synthesis/`"],
        ], [1800, 3400, 2200, 2400]),
        h2("Discovery: product analytics", "g-analytics"),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/activation-analysis`", "Activation read with the Setup → Aha → Habit framework", "Onboarding flow and data (or a connected analytics tool)", "Bottlenecks and stage-rate baselines"],
          ["`/retention-analysis`", "Cohort and retention analysis", "Retention data (or a connected analytics tool)", "Retention drivers and churn factors"],
        ], [1800, 3400, 2200, 2400]),
        h2("Prototyping", "g-proto"),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/prototype`", "Routes to the right prototyping tool and writes the prompt or spec", "A PRD, feature description or sketch", "A copy-paste prompt (v0, Lovable, Bolt, …) or a static HTML prototype"],
          ["`/prototype-feedback`", "Build → review → iterate loop for a prototype", "A prototype link or description", "Structured feedback mapped to the PRD"],
          ["`/napkin-sketch`", "ASCII wireframes or a capture of an existing screen", "The screen or feature", "A wireframe to react to"],
          ["`/journey-map`", "User and customer journey maps", "The journey and persona", "A journey map in `customers/research-synthesis/`"],
        ], [1800, 3400, 2200, 2400]),
        h2("OS admin & governance", "g-admin"),
        p("Setting the Work OS up, and keeping the repository honest before and after a feature ships. Mostly the Work OS admin's — described in the Setup section."),
        table(["Skill", "What it does", "You give it", "You get"], [
          ["`/customize-os`", "Adapts the Work OS to your company — naming, business context, templates, auto-sync mode", "Your company's basics and example documents", "Customized context files + a readout; resumable"],
          ["`/auto-sync`", "The switch for the automatic saving and syncing (on / off / status)", "The mode", "The current state and the gated list"],
          ["`/propose`", "Opens the pull request that carries your gated changes to the admins", "Nothing — reads what's waiting on your branch", "A pull request with a plain-language description"],
          ["`/connect-mcps`", "Connects a tool so skills read it live", "The tool name", "A tested connection, wired into the skills that use it"],
          ["`/connect-code`", "Registers product code repositories and grants read-only access on your computer", "The repository link", "A registry entry; local read access"],
          ["`/context-update`", "Folds new material into the wiki — threads, documents, facts — routed by type", "A path, pasted content, or nothing (sweep the inbox)", "Updated pages, navigation and ledger"],
          ["`/wiki-lint`", "Health-checks the repository and fixes mechanical drift", "Nothing", "A dated health report; fixes applied; suggestions listed"],
          ["`/feature-launch-gate`", "Pre-launch completeness check of the repository for a feature", "The feature", "A ship / not-yet verdict"],
          ["`/session-retro`", "End-of-session sweep for durable takeaways", "Nothing", "Rules routed to the right place, or a proposal"],
        ], [1800, 3400, 2200, 2400]),
        h2("Agents", "agents"),
        p("You don't run agents directly — skills do. Knowing them explains where a report's perspectives come from."),
        table(["Agent", "Perspective", "Used by"], [
          ["Customer voice", "Evaluates from the customer's point of view", "`/prd-challenge`, `/strategy-sprint`"],
          ["Designer reviewer", "Product design lens on specs and user experience", "`/prd-challenge`, `/job-spec-challenge`"],
          ["Engineer reviewer", "Engineering feasibility and technical risk", "`/prd-challenge`, `/job-spec-challenge`"],
          ["Executive reviewer", "Strategic business perspective", "`/prd-challenge`, `/strategy-sprint`"],
          ["Legal advisor", "Legal, compliance and regulatory concerns, early", "`/prd-challenge`, `/job-spec-challenge`"],
          ["Skeptic", "Challenges assumptions, plays devil's advocate", "`/prd-challenge`"],
          ["UX research analyst", "Research perspective; spots evidence gaps", "`/prd-challenge`"],
          ["PO / BA reviewer", "Rules, acceptance criteria and ticket-cuttability of a job spec", "`/job-spec-challenge`"],
          ["QA lead reviewer", "Testability of a job spec as written", "`/job-spec-challenge`"],
          ["Code explorer", "Read-only investigator of your product code; returns findings with file-and-line citations", "`/code-qa`"],
        ], [2200, 4400, 2800]),
      ]},

      { id: "context", title: "Context system", audience: "Everyone", time: "6 min read", blocks: [
        lead("The context system is everything Claude knows before you ask — the folders and files of the Work OS repository. This article lists them item by item: what each holds and how it is used. Same terminology as the programme: plain Markdown and YAML in folders, versioned in {gh:GitHub|az:Azure Repos}, tool-agnostic."),
        h2("Six kinds of item", "types"),
        table(["Type", "What it means", "How to treat it"], [
          ["Steering file", "Loaded automatically or read first; shapes how Claude behaves. Most are gated.", "Change deliberately — every edit goes through the 🔒 prompt and an admin's approval"],
          ["Registry", "Machine-readable lookup (YAML) with a single writer; skills update entries", "Rarely edited by hand"],
          ["Living page", "Current truth, edited in place and kept up to date", "Read first for \"what's the state of …\""],
          ["Raw material", "Accumulating evidence — transcripts, records, monitoring runs", "Append; never rewrite history"],
          ["Deliverable", "Skill outputs — specs, plans, reports, results", "Written by skills; iterate through the skill"],
          ["Templates & guides", "Stable reference material — copy it, don't edit it", "Templates are gated"],
        ], [1800, 4400, 3200]),
        h2("Repository root and the OS itself", "root"),
        table(["Item", "Type", "What's in it", "How it's used"], [
          ["`CLAUDE.md`", "Steering file", "Master context, loaded every session: company fundamentals, the document index with read orders, the four rules, governance pointers", "Start of every session; its read-order table routes common questions; its fundamentals block mirrors `business-info.md`"],
          ["`.claude/skills/`", "Steering file", "The skills — one folder per `/command`", "See [Skills and agents](#/overview/skills)"],
          ["`.claude/agents/`", "Steering file", "Reviewer personas + the code explorer", "Spun up by `/prd-challenge`, `/job-spec-challenge`, `/strategy-sprint`, `/code-qa`"],
          ["`.claude/team-learnings.md`", "Steering file", "Cross-cutting behaviour rules distilled from corrections (short, hard-capped)", "Injected at every session start; `/session-retro` and the capture loop route durable takeaways here"],
          ["`governance/`", "Steering file", "`write-policy.yaml` (the gated list + auto-sync settings), the write-back contract, the ingestion ledger, health reports, pending proposals", "The admin surface — see [How changes reach the team](#/overview/changes)"],
          ["`os-installation/`", "Templates & guides", "Install and setup guides, customization status, tool-integration logs", "Reference for the Work OS admin"],
          ["`Documentation/`", "Templates & guides", "This documentation: the site, one Word edition per platform, and the source they are built from", "Read it, share it; change it through the gated flow"],
        ], [2300, 1400, 3200, 2500]),
        h2("product-development/ — the top level", "pd"),
        table(["Item", "Type", "What's in it", "How it's used"], [
          ["`feature-index.yaml`", "Registry", "Master lookup: every feature mapped to its PRD, plan, metrics, experiments, tickets and initiative", "First stop for any \"state of feature X\" question; every repo-writing skill updates it"],
          ["`inbox/`", "Raw material (drop zone)", "Transient landing zone for integration drops — transcripts, exports. Nothing lives here for long", "Swept by `/context-update`; transcripts are handed to `/process-meeting`, which files them to their home"],
        ], [2300, 1400, 3200, 2500]),
        h2("product-development/product/", "product"),
        table(["Item", "Type", "What's in it", "How it's used"], [
          ["`strategy/business-context/business-info.md`", "Steering file", "Source of truth for company, product, ICP, personas, pricing, go-to-market and market", "Read in full before any PRD, pricing, positioning, metric, competitive or strategy work"],
          ["`strategy/business-context/segmentation-matrix.md`", "Steering file", "Account counts and ARR by vertical × size band × use case", "The only source for segment sizing"],
          ["`strategy/business-context/stakeholders.md`", "Steering file", "Stakeholder profiles: what each cares about, how they like to be communicated with", "Buy-in plans and tailored communication (`/status-update`, `/slack-message`)"],
          ["`strategy/current-quarter.md`", "Steering file", "This quarter's OKRs, bets and the explicit \"not doing\" list — one screen, replaced each quarter", "Injected at session start; grounds every prioritization call"],
          ["`strategy/roadmaps/`", "Living page", "Time-boxed roadmaps plus long-range vision documents", "Where plans beyond the current quarter live"],
          ["`strategy/frameworks/` · `okr-guide.md`", "Templates & guides", "Strategy frameworks and how-we-write-OKRs guidance", "Pulled by `/strategy-sprint`, `/write-prod-strategy`; read when refilling the quarter"],
          ["`initiatives/`", "Living page", "One page per current work effort: status, artifacts, decisions, open loops", "First stop for \"state of initiative Y\"; created by `/prd-draft`, rolled up by `/weekly-review`"],
          ["`customers/accounts/{account}/`", "Living page + raw material", "One folder per customer: `account-context.md` (current truth) + calls with summaries and raw transcripts", "`/process-meeting` files calls here; \"what did customer Y say\" reads the summary first"],
          ["`customers/accounts/portfolio.yaml`", "Registry", "Cross-account registry: segment, health, ARR per customer", "Read by `/portfolio-pulse`"],
          ["`customers/feature-requests/`", "Raw material", "One dated record per customer feature request: evidence, draft ticket, tracker state", "Clustered by `/prioritize-requests`; pushed by `/create-tickets`"],
          ["`customers/research-synthesis/`", "Deliverable", "Cross-interview synthesis reports and journey maps", "Written by `/user-research-synthesis`, `/journey-map`; evidence base for PRDs"],
          ["`competitive-research/`", "Living page + raw material", "`competitive-landscape.md` (tiered list, positioning), `competitive-matrix.md` (capability comparison), one `competitors/{slug}/` teardown per competitor, `intel/` monitoring records", "First stop for \"who do we compete with / how do we compare on X\"; maintained by `/competitor-analysis`"],
          ["`decisions/`", "Raw material", "One dated file per decision: reasoning, options considered, tradeoff accepted", "Answers \"why did we choose Z\"; written by `/decision-log-entry`"],
          ["`meetings/`", "Raw material", "Internal meeting records by series and event: docs, transcripts, summaries; retros", "`/process-meeting` files transcript + summary here and routes decisions onward"],
          ["`PRDs/{area}/`", "Deliverable", "PRDs by product area; `examples/` worked examples; `reviews/` challenge reports; job breakdowns and job specs", "`/prd-draft`, `/prd-challenge`, `/jobs-breakdown`, `/job-spec-draft`, `/create-tickets`"],
          ["`reports/` · `planning/` · `launches/`", "Deliverable", "Weekly reviews and pulses; daily and weekly plans; launch checklists and gate records", "`/weekly-review`, `/portfolio-pulse`, `/status-update`; `/daily-plan`, `/weekly-plan`; `/launch-checklist`, `/feature-launch-gate`"],
          ["`handbook/templates/`", "Templates & guides", "Blank templates with bracketed placeholders (gated)", "Copied — never edited in place — by skills scaffolding new pages"],
          ["`handbook/writing-guides/` · `de-risk-a-bet.md`", "Templates & guides", "Writing conventions by audience; the canonical skill chain for stress-testing a bet", "\"How should I write this?\"; entry point for any new bet"],
        ], [2600, 1400, 3000, 2400]),
        h2("product-development/analytics/", "analytics"),
        table(["Item", "Type", "What's in it", "How it's used"], [
          ["`data-catalog.yaml`", "Registry", "Warehouse table registry: owner, refresh, upstream, grain, used-by", "\"Where's the data for X\" — check before opening schema documents"],
          ["`metrics/{area}/` · `queries/{area}/`", "Living page", "Metric definitions (numerator, denominator, caveats, owner) and reusable SQL with a *Last verified* date", "\"How do we calculate metric M\"; `/feature-metrics` writes here"],
          ["`schemas/{area}/` · `dashboards/{area}/`", "Living page", "Table and event schema documentation; dashboard definitions and links", "Column-level detail; where each number is watched"],
          ["`experiments/{area}/` · `investigations/{area}/`", "Deliverable", "Experiment designs and results; ad-hoc analytical deep dives", "`/experiment-decision`, `/experiment-metrics`, `/feature-results`"],
        ], [2600, 1400, 3000, 2400]),
        h2("product-development/engineering/", "engineering"),
        table(["Item", "Type", "What's in it", "How it's used"], [
          ["`code-repos.yaml`", "Registry", "Your product code repositories: purpose, coverage keywords, entry points, access tier", "Filled by `/connect-code`; how `/code-qa` finds the right code — see [Connect your product's code](#/setup/code)"],
          ["`code-grounding.md`", "Steering file", "The rules every claim about product code follows: access tiers, citations, honesty rules", "Implemented by `/code-qa` and `/connect-code`"],
          ["`codebases/`", "Living page", "Maps of large repositories — a table of contents per repository", "Fallback grounding for `/code-qa`; refreshed by `/connect-code --refresh`"],
          ["`plans/` · `tech-constraints.md`", "Deliverable / living page", "Implementation plans by area; technical constraints and the do-not-re-implement registry", "Engineers' check-in surface; text fallback for `/create-tickets`"],
        ], [2600, 1400, 3000, 2400]),
        callout("tip", "Two habits keep the context system trustworthy: **summaries first, raw data in subfolders** (a one-hour call becomes a short summary; the transcript stays underneath), and **every folder has a `CLAUDE.md` navigation file** that lists what's inside — Claude reads those to find its way, and `/wiki-lint` keeps them honest."),
      ]},

      { id: "changes", title: "How changes reach the team", audience: "Everyone", time: "3 min read", blocks: [
        lead("What happens between \"Claude finished a response\" and \"the team can see it\" — in plain words, and what you will see in {gh:GitHub|az:Azure Repos}."),
        h2("Everyday changes", "everyday"),
        steps([
          "You ask Claude for something — a meeting summary, a decision record, a customer note. Claude writes the file.",
          "When Claude finishes the response, auto-sync saves the change to your personal branch in the shared repository (a branch is a private working line; yours is named `sync/<your git name>`).",
          "Auto-sync opens a small pull request from that branch into `main` — the team's shared line — and it merges by itself. Nobody has to look at it.",
        ]),
        callout("check", "On the repository page you'll see the file on `main` within about a minute, and under **Pull requests › {gh:Closed|az:Completed}** a pull request called *\"context: sync from sync/<name>\"*."),
        h2("Changes to gated files", "gated"),
        p("Gated files are the ones that steer the whole Work OS. The authoritative list lives in `governance/write-policy.yaml` (`tiers → gated`); everything else is an everyday file:"),
        bullets([
          "`CLAUDE.md` · `governance/` · `os-installation/` · `Documentation/` · `.claude/` · `.github/`",
          "`product-development/feature-index.yaml`",
          "`product-development/product/strategy/business-context/` (business-info, stakeholders, segmentation)",
          "`product-development/product/handbook/templates/`",
          "`product-development/engineering/`",
        ]),
        steps([
          "You ask Claude to change a gated file. Before writing, Claude shows a **🔒 GATED FILE** prompt — you read the change and approve it.",
          "When Claude finishes, auto-sync saves the change to your personal branch — but not to `main`. It waits there while you keep iterating.",
          "When you're done, you say **\"propose the gated changes\"**. Claude opens a pull request with a plain-language description of everything that changed.",
          "A Work OS admin reviews it — in {gh:GitHub|az:Azure Repos}, or by asking their own Claude — approves, and {gh:merges|az:completes} it. {gh:GitHub|az:Azure Repos} won't let anyone else. (An admin publishing their *own* gated change can ask Claude to do all three at once — see [Customize the Work OS, step 3](#/setup/customize/z3).)",
          "Next time Claude finishes a response, your branch tidies itself — the approved change is now part of `main` for everyone.",
        ]),
        callout("check", "The pull request is titled *\"gated: …\"* and shows {gh:**Review required — Code owner review** from `os-admins`|az:**OS-Admins** as a required reviewer}."),
        h2("Two people, one file", "conflicts"),
        p("If two people change the same file, auto-sync tries to combine the changes; when it can't, it tells the person whose save is waiting exactly what to do (see [Troubleshooting](#/setup/troubleshooting)). Nothing is lost — the change stays on their branch."),
      ]},
    ]},

    // ================================================================= SETUP
    { id: "setup", title: "Setup", articles: [

      { id: "overview", title: "Overview", audience: "Everyone — read first", time: "5 min read", blocks: [
        lead("This guide helps you set up and customize the Work OS for your organization: one shared repository that every teammate and Claude Code work in, adapted to your company, and — where useful — connected to your tools and your product's code. Three roles, three stages, about half a day in total."),
        h2("What you'll have at the end", "outcome"),
        bullets([
          "**One source of truth.** Every teammate's Claude reads the same repository — the same business context, decisions and skills, always current.",
          "**Everyone contributes, safely.** Everyday additions (a meeting summary, a decision, a customer insight) reach the shared repository by themselves. Changes to the core files that steer the Work OS — its rules, templates and business context — are *proposed* and approved by a Work OS admin. That is how the Work OS improves over time without anyone breaking it.",
          "**No git skills required.** Claude does the saving, syncing and proposing. People write, review and approve.",
        ]),
        h2("Who does what", "roles"),
        table(["", "Repository admin", "Work OS admin", "Work OS user"], [
          ["Who", "Whoever administers your {gh:GitHub organization|az:Azure DevOps project} — often IT or DevOps", "One person from your company (permanent) + the SoftServe program lead (temporary). At least two at all times", "Everyone on the team"],
          ["Sets up", "The repository, the admin group, access, the branch rule", "The Work OS itself: their own computer, customization, tools and code connections", "Their own computer"],
          ["Day to day", "Nothing — unless access or rules change", "Approves proposed changes to gated files; keeps the Work OS healthy", "Works in the Work OS; everyday changes save by themselves; proposes changes to gated files"],
          ["Needs a Work OS account?", "No — a {gh:GitHub|az:Azure DevOps} account is enough", "Yes, and membership of the admin group", "Yes"],
        ], [1800, 2500, 2700, 2400]),
        platform("github", p("On GitHub: the repository admin is an *organization owner*; Work OS admins are members of the team **`os-admins`** (Write access, reviewer for gated files, may bypass the branch rule); Work OS users have *Write* access.")),
        platform("azure", p("On Azure Repos: the repository admin is in *Project Administrators*; Work OS admins are members of the group **`OS-Admins`** (required reviewer for gated files, may bypass branch policies); Work OS users are in the project's *Contributors* group.")),
        h2("The setup flow", "flow"),
        p("Three stages, in this order. Each stage is one or more articles in this section — the names below are the article names."),
        seq([
          { who: "Stage 1 · Repository admin", what: "**Set up the repository** — import the Work OS from SoftServe, create the admin group, give people access, protect the main branch. Done in the {gh:GitHub|az:Azure DevOps} web interface.", time: "about 30 minutes", link: "#/setup/repository", label: "Set up the repository" },
          { who: "Stage 2 · Work OS admin", what: "**Set up your computer**, then **Customize the Work OS** (which also switches auto-sync on and ends with the first access test). Optional, when you're ready: **Connect your tools** and **Connect your product's code**.", time: "2–3 hours, resumable", link: "#/setup/customize", label: "Customize the Work OS" },
          { who: "Stage 3 · All Work OS users", what: "**Set up your computer** and check that your work reaches the team. If the team uses connected tools or code, add your own part of those two articles.", time: "about 20 minutes each", link: "#/setup/computer", label: "Set up your computer" },
        ]),
        callout("note", "The order matters: Stage 3 can only start after the repository exists (Stage 1) and the Work OS admin has finished customization (Stage 2)."),
        h2("Two terms you will see everywhere", "terms"),
        terms([
          { term: "Gated files", def: "The small set of files that steer the whole Work OS — its rules and settings, the document templates, and the business context (for example `business-info.md`). Changing one needs a Work OS admin's approval. Everything else is an *everyday file*. The full list is in [How changes reach the team](#/overview/changes/gated)." },
          { term: "Auto-sync", def: "The Work OS feature that saves your work to the shared repository every time Claude finishes a response — you never run git commands. Everyday files land straight away; gated changes wait until you say *\"propose the gated changes\"*, which opens a request a Work OS admin approves in {gh:GitHub|az:Azure Repos} (admins publish their own in one go). Details: [How changes reach the team](#/overview/changes)." },
        ]),
      ]},

      // ------------------------------------------------------------- stage 1 · repository admin
      { id: "repository", title: "Set up the repository", audience: "Stage 1 · Repository admin", time: "about 30 minutes, once", blocks: [
        lead("You are the person who administers your {gh:GitHub organization|az:Azure DevOps project}. The repository you are about to create is the team's shared knowledge base: Claude Code reads it on each teammate's computer before it drafts anything and saves their finished work straight back into it — so everyone needs read *and* write access, not read-only, while step 4 protects `main` so that the few files steering the whole system still need a Work OS admin's approval. In this article you import the Work OS from SoftServe, create the admin group, give people access, and protect the main branch — all in the {gh:GitHub|az:Azure DevOps} web interface. Nothing to install."),
        h2("Before you start", "before"),
        checklist([
          "You can create repositories and change their settings in your {gh:GitHub organization (you are an organization owner)|az:Azure DevOps project (you are in Project Administrators)}.",
          "The SoftServe team has given you access to the source repository — the initial version of the Work OS — or a token to import it. See step 1.",
          "You have the names and e-mail addresses of the **initial Work OS admins**: one person from your company (permanent) and the SoftServe program lead (temporary). Both need an account in your {gh:GitHub organization|az:Azure DevOps organization} — invite the SoftServe person as {gh:an outside collaborator or organization member|az:a project user (a Basic access level is enough)}.",
          "You have the list of **initial Work OS users** (names and e-mail addresses).",
        ]),
        platform("github", callout("note", "Protecting `main` (step 4) needs **GitHub Team** or Enterprise Cloud while the repository is private: on the **Free** plan neither rulesets nor branch protection apply to private repositories. Check the plan now — step 4 covers what to do if the organization is on Free.")),

        h2("Step 1 — Get the Work OS from [SoftServe Work OS on GitHub](" + SRC + ")", "s1"),
        p("The initial version of the repository comes from the SoftServe team. Ask them for access to the source repository (and, if it is private, for the token to import it). Then import it into your {gh:organization|az:project} — no command line needed."),
        platform("github", steps([
          "In GitHub, open the **+** menu in the top-right corner and select **Import repository**.",
          "**Your source repository details › The URL for your source repository:** paste the URL SoftServe gave you. If it asks for credentials, enter the username and token from SoftServe.",
          "**Owner:** your organization. **Repository name:** `work-os` (or your own name). **Privacy:** **Private**.",
          "Select **Begin import** and wait for the confirmation e-mail or the page to finish.",
          "Open the new repository → **Settings › General › Default branch** — it must be **`main`**. If it isn't, switch it there.",
        ])),
        platform("azure", steps([
          "In your project, go to **Repos › Files**. Open the repository dropdown at the top of the page and select **Import repository**.",
          "**Repository type:** Git. **Clone URL:** paste the URL SoftServe gave you. If the source is private, tick **Requires authentication** and enter the username and token from SoftServe.",
          "**Name:** `work-os` (or your own name). Select **Import**.",
          "When the import finishes, go to **Repos › Branches** and check that **`main`** is the default branch (⋯ menu → *Set as default branch* if not).",
        ])),
        callout("expected", "The repository page shows `CLAUDE.md`, `governance/`, `product-development/`, `os-installation/` and the other folders on `main`."),

        h2("Step 2 — Create the Work OS admin group", "s2"),
        platform("github", steps([
          "Go to your organization page → **Teams › New team**.",
          "**Team name:** `os-admins`. Visibility: *Visible*. Select **Create team**.",
          "On the team page, **Members › Add a member** — add the initial Work OS admins (your company's person and the SoftServe program lead).",
        ])),
        platform("azure", steps([
          "Go to **Project settings › Permissions** and select **New group**.",
          "**Name:** `OS-Admins`. **Members:** add the initial Work OS admins (your company's person and the SoftServe program lead). Select **Create**.",
        ])),
        callout("expected", "The group exists and lists at least two people. Keep it at two or more at all times, so an admin's own change can be approved by another admin."),

        h2("Step 3 — Give people access to the repository", "s3"),
        platform("github",
          steps([
            "Open the repository → **Settings › Collaborators and teams**.",
            "**Add teams** → `os-admins` → role **Write**.",
            "**Add people** (or add the team everyone is already in) → every Work OS user → role **Write**.",
          ]),
          callout("note", "Everyone — admins included — gets *Write*. What makes a Work OS admin special is membership of `os-admins`: step 4 makes that team the reviewer for gated files and lets it bypass the branch rule."),
          callout("expected", "The Collaborators page lists `os-admins` and every Work OS user, all with *Write*. Invited people receive an e-mail and must accept it.")),
        platform("azure",
          steps([
            "Go to **Project settings › Permissions › Contributors › Members** and make sure every Work OS user and admin is listed (add the missing ones with **Add**).",
            "Go to **Project settings › Repositories**, select the Work OS repository, open the **Security** tab.",
            step("Select the **OS-Admins** group in the left list and set:",
              table(["Permission", "OS-Admins"], [
                ["Bypass policies when completing pull requests", "**Allow**"],
                ["Bypass policies when pushing", "**Allow**"],
                ["Force push (rewrite history, delete branches and tags)", "**Allow**"],
                ["Contribute · Create branch · Contribute to pull requests", "Allow"],
              ], [6400, 2000])),
            "Leave the **Contributors** group as it is. Its *Bypass* and *Force push* permissions show **Not set** — that already means \"no\".",
          ]),
          callout("dont", "Set the Contributors permissions to **Deny**. In Azure DevOps a Deny wins over an Allow, and your Work OS admins are Contributors too — a Deny would block them as well."),
          callout("expected", "Under **Security**, `OS-Admins` shows *Allow* on the bypass permissions; Contributors show *Not set* there and *Allow* on Contribute.")),

        h2("Step 4 — Protect the main branch", "s4"),
        p("This is the rule that makes admin approval enforceable: everyone works through pull requests, everyday pull requests merge by themselves, and a pull request that touches a gated file needs the admin group."),
        platform("github",
          steps([
            "Open the repository → **Settings › Rules › Rulesets › New ruleset › New branch ruleset**.",
            "**Ruleset name:** `main-pr-only`. **Enforcement status:** *Active*.",
            "**Bypass list › Add bypass** → the team **`os-admins`** → mode **Always**. (Admins may skip the rule — that is how they merge approved gated changes.)",
            "**Target branches › Add target › Include default branch**.",
            "Under **Rules**, tick **Require a pull request before merging**. Set **Required approvals** to **0** and tick **Require review from Code Owners**. Leave the other sub-options off. Keep **Block force pushes** ticked.",
            "Optional: tick **Require status checks to pass** and add `wiki-lint` — every pull request then passes the Work OS health check first.",
            "Select **Create**.",
            "Go to **Settings › General**, scroll to **Pull Requests**, tick **Allow auto-merge** and **Automatically delete head branches**. Keep **Allow rebase merging** on. Save.",
          ]),
          callout("note", "**Who are the \"Code Owners\"?** A file in the repository, `.github/CODEOWNERS`, that names `os-admins` as the reviewer for every gated file. The Work OS admin fills in your organization's name there during [Customize the Work OS](#/setup/customize) — until then gated pull requests can merge without review, which is fine during setup."),
          callout("note", "**On the GitHub Free plan** a private repository cannot be protected at all — rulesets and branch protection are both limited to public repositories there. Upgrade the organization to **Team**, or run without the rule for now: Claude still shows the 🔒 prompt before every gated change and still routes it through a pull request, but nothing stops a direct push to `main`, so admin approval is a team convention rather than something GitHub enforces."),
          callout("dont", "Create a *push ruleset* for the gated folders. It would also block the branches that pull requests come from, and nobody could propose a change."),
          callout("expected", "**Settings › Rules** shows `main-pr-only` as *Active*. A pull request that changes a gated file will show *Review required — Code owner review*; one that doesn't will merge by itself. Members of `os-admins` can still push to `main` directly.")),
        platform("azure",
          steps([
            "Go to **Repos › Branches**, hover over `main`, open the **⋯** menu, select **Branch policies**.",
            "Leave **Require a minimum number of reviewers** *off*. (Turning it on would make every everyday pull request wait for a person.)",
            "Under **Automatically included reviewers**, select **+**. **Reviewers:** `OS-Admins`. **Policy requirement:** *Required*.",
            step("**For pull requests affecting these folders** (the path filter): paste this line exactly:",
              code([ADO_FILTER], "Path filter"),
              callout("tip", "This is the list of gated files in the form Azure expects. If the Work OS admin later changes the list, they will send you the new line to paste here.")),
            "Tick **Allow requestors to approve their own changes** — so a Work OS admin can approve a change they proposed themselves.",
            "**Activity feed message:** `Gated Work OS file — needs OS-Admins approval`. Select **Save**.",
            "Optional: under **Limit merge types**, allow *Squash merge* and *Rebase and fast-forward*.",
          ]),
          callout("note", "Any *required* policy on `main` makes it pull-request-only for everyone outside `OS-Admins`. That's intended — everyday pull requests still complete by themselves because they don't touch the folders in the path filter."),
          callout("expected", "**Branch policies** for `main` shows one required reviewer policy for `OS-Admins` with the path filter. A pull request that changes a gated file will list `OS-Admins` as required; one that doesn't will complete by itself.")),

        h2("Step 5 — Hand over to the Work OS admin", "s5"),
        steps([
          "Send the Work OS admins the repository link and confirm they are in the admin group.",
          "Tell them the initial users have access, so they can invite the team as soon as customization is done.",
        ]),
        callout("pass", "A Work OS admin can open the repository page. A Work OS user can open it too. The rule on `main` is active. Stage 1 is complete — the Work OS admin continues with Stage 2: [Set up your computer](#/setup/computer), then [Customize the Work OS](#/setup/customize)."),
      ]},


      // ------------------------------------------------------------- stage 2/3 · everyone
      { id: "computer", title: "Set up your computer", audience: "Stage 2 (Work OS admin) and Stage 3 (everyone)", time: "about 20 minutes, once", blocks: [
        lead("Get your own copy of the Work OS on your computer, connect it to the shared repository, and check that your work reaches the team. After a one-time install (step 1) you do everything in the **Claude Code desktop app** — Claude runs the technical steps for you."),
        h2("Before you start", "before"),
        checklist([
          "You have access to the Work OS repository. If you don't yet, ask the **repository admin** — through your organization's usual access request, if it has one — for {gh:**Write** access to the repository|az:membership of the project's **Contributors** group; that is what lets you read, clone and contribute}. You can tell you have it when the repository link they sent opens in your browser and shows the files (`CLAUDE.md`, `governance/`, `product-development/` …). {gh:If you received an invitation e-mail from GitHub, accept it first.|az:If the page asks you to sign in, use your Azure DevOps account; if it then says you don't have access, you are not in the group yet — ask again.}",
          "The **Work OS admin** has told you the Work OS is ready (Stage 2 done: customized, auto-sync on). *Skip this line if you are the Work OS admin doing Stage 2 yourself — you'll do that next.*",
          "You can install software on your computer, or you know how your organization provides it — an internal software catalog or self-service client, or a request to IT. Step 1 needs two tools: **Claude Code** and **Git**.",
        ]),
        h2("Step 1 — Install Claude Code and Git", "c1"),
        p("Two tools, once. Get both the way your organization provides software — its software catalog or self-service client if it has one, otherwise from the links below."),
        steps([
          step("**Git** — the tool the Work OS runs on: it brings the repository to your computer, and auto-sync uses it to save your work. Install it from your organization's software catalog, or from [git-scm.com/downloads](https://git-scm.com/downloads), accepting the defaults. You'll check it in step 3.",
            callout("note", "**Windows:** install Git *before* you open Claude Code — on Windows, Claude Code uses Git for Windows to run the Work OS's automation. If Claude Code is already open, close it and open it again after installing Git.")),
          step("**Claude Code desktop app** — install it from your organization's software catalog, or from [claude.ai/download](https://claude.ai/download). Open it and sign in with the account your organization uses for Claude — usually your work e-mail. If you're not sure which account, the Work OS admin knows.",
            callout("expected", "Claude Code opens and shows you as signed in, and asks for a project folder — that's step 2.")),
        ]),
        h2("Step 2 — Open a folder for the Work OS", "c2"),
        steps([
          "Create an empty folder on your computer, for example `Documents/work-os`.",
          "In the Claude Code desktop app, start a new session and choose that folder as the project folder.",
        ]),
        h2("Step 3 — Ask Claude to bring in the Work OS", "c3"),
        steps([
          step("First, check that Git is in place — ask Claude:", say("Check that git is installed and tell me the version"),
            callout("expected", "Claude answers with a version, for example `git version 2.4x`. If it says Git is missing, install it (step 1) and start a new session.")),
          step("Copy the repository link from {gh:the repository page → **Code › HTTPS**|az:**Repos › Files › Clone**} and ask Claude:",
            say("Clone <paste the repository link> into this folder, so that the repository's files are directly in it (git clone <link> .)"),
            callout("expected", "Claude confirms the clone and you see `CLAUDE.md`, `governance/`, `product-development/` … in the folder.")),
          step("Start a **new session** in the same folder — Claude now loads the Work OS.",
            callout("expected", "Claude opens with a short briefing: recent decisions, the current quarter, active initiatives. That's the Work OS talking.")),
        ]),
        h2("Step 4 — Tell Claude who you are", "c4"),
        steps([
          step("Auto-sync signs your changes with your name and e-mail. Ask Claude:",
            say("Set my git name to <Your Name> and my git e-mail to <you@company.com> for this repository"),
            callout("expected", "Claude confirms both values.")),
        ]),
        h2("Step 5 — Sign in to {gh:GitHub|az:Azure DevOps} once", "c5"),
        p("Auto-sync opens and merges pull requests on your behalf. For that it uses the {gh:GitHub|az:Azure} command-line tool, signed in as you. Claude handles it; you only confirm in the browser."),
        platform("github", steps([
          step("Ask Claude:",
            say("Sign me in to GitHub with the GitHub CLI (gh) using the browser flow. If gh is not installed, install it first."),
            callout("expected", "Claude shows a one-time code and a github.com link. Open the link, enter the code, and authorize. Claude then confirms you are signed in.")),
        ])),
        platform("azure", steps([
          step("Ask Claude:",
            say("Sign me in to Azure DevOps with the Azure CLI (az login with a device code) and add the azure-devops extension. If az is not installed, install it first."),
            callout("expected", "Claude shows a code and a microsoft.com link. Open the link, enter the code, sign in with your work account. Claude then confirms you are signed in.")),
        ])),
        callout("tip", "Installing a tool may ask for your computer password. That is normal — it happens once."),
        h2("Step 6 — Check that auto-sync is on", "c6"),
        steps([
          step("Ask Claude:", say("/auto-sync status"),
            callout("expected", "**ON**, mode **pr**. If it says off and you are a Work OS user, ask the Work OS admin — the switch is shared and only admins turn it on. If you *are* the Work OS admin doing Stage 2, it will be off: skip step 7 for now and continue with [Customize the Work OS](#/setup/customize) — auto-sync is switched on there.")),
        ]),
        h2("Step 7 — Check that your work reaches the team", "c7"),
        p("Two quick tests: an everyday change that lands by itself, and a gated change that waits for an admin."),
        steps([
          step("Ask Claude to create an everyday file, then wait until Claude finishes the response — that's when auto-sync runs:",
            say("Create a short test meeting summary at product-development/product/meetings/other/summaries/<today's date>-access-test-<your name>.md and mark it clearly as TEST"),
            callout("check", "Within about a minute the file is on `main` (repository page → the folder). Under **Pull requests › {gh:Closed|az:Completed}** there is a pull request *\"context: sync from sync/<your name>\"* that merged by itself.")),
          step("Ask Claude to change a gated file. A **🔒 GATED FILE** prompt appears — read it and approve. Wait until Claude finishes.",
            say("In business-info.md, correct or fill in one line"),
            callout("expected", "Claude reports the change is saved on your branch, not on `main`, and that there is no pull request yet.")),
          step("Send it for approval:", say("propose the gated changes"),
            callout("check", "Claude reports the pull request link. Open it: it is titled *\"gated: …\"*, shows {gh:**Review required — Code owner review**|az:**OS-Admins** as a *Required* reviewer}, and the {gh:Merge|az:Complete} button is disabled for you.")),
          step("Ask a Work OS admin to approve and merge it — in {gh:GitHub|az:Azure Repos}, or by telling their own Claude *\"approve and {gh:merge|az:complete} pull request <number>\"*.",
            callout("check", "Your change is on `main`. The next time Claude finishes a response, it notes that everything on your branch has landed and the branch is clean.")),
        ]),
        callout("pass", "The everyday file landed by itself; the gated change could not be merged by you; it landed after an admin approved it. You're set — work as usual from here. If your team has connected tools or code, finish with your part of [Connect your tools](#/setup/tools) and [Connect your product's code](#/setup/code)."),
        callout("tip", "**Clean-up:** ask Claude to delete the TEST summary — an everyday change, it lands by itself. Keep the `business-info.md` edit if it was a real correction."),
      ]},


      // ------------------------------------------------------------- stage 2 · work OS admin

      { id: "customize", title: "Customize the Work OS", audience: "Stage 2 · Work OS admin", time: "1–2 hours, once — resumable", blocks: [
        lead("You own the Work OS for your team. In this article you run the guided customization — which adapts the Work OS to your company and switches auto-sync on{gh:, name the approver team|az:}, publish the changes for everyone, and do the first access test. After that you invite the users."),
        callout("note", "**Work in progress.** The detailed walkthrough of the `/customize-os` conversation (naming, business context, templates) is being written. The steps below are complete for the access and auto-sync part."),
        h2("Before you start", "before"),
        checklist([
          "You have finished [Set up your computer](#/setup/computer) steps 1–6 (install, folder, clone, name, sign-in; auto-sync will show *off* — expected).",
          "The repository admin has confirmed you are in the {gh:`os-admins` team|az:`OS-Admins` group}.",
          "You have your company's basics at hand: product, customers, how you name your documents (PRD / brief / one-pager …), two to four example documents in your house format.",
        ]),
        h2("Step 1 — Run the guided customization", "z1"),
        p("`/customize-os` is a conversation. It reads what is already customized, asks only for what is missing, writes the customized context files behind the 🔒 prompt, and ends with a readout of what changed and what is still needed. You can stop any time and continue later with `/customize-os continue`."),
        steps([
          step("Ask Claude:", say("/customize-os")),
          "Answer the questions: how your company names its documents (keep the Work OS names or map them to yours), your business context, your document formats (from example documents). Approve each 🔒 prompt after reading the change.",
          step("Near the end Claude asks which **auto-sync mode** the team wants. Answer **pr** (the mode for a protected `main` — changes move through pull requests) and say **yes** to switch it on now.",
            callout("expected", "Claude confirms **\"Auto-sync is ON — pr mode (main is pull-request-only)\"** and lists the gated files. From the next response on, your work is saved to your branch automatically; the customization changes are waiting there for approval.")),
          "Read the closing readout: what changed and where, and what is still open (Critical / Other). `os-installation/customization-status.md` keeps the state for the next session.",
        ]),
        h2("Step 2 — Name the approvers", "z2"),
        platform("github",
          callout("why", "GitHub reads who must approve gated changes from the file `.github/CODEOWNERS`. The Work OS generates that file from one line in `governance/write-policy.yaml`. Until you fill in that line, GitHub ignores the file and gated pull requests could merge without approval."),
          steps([
            step("Ask Claude — replace `<your-org>` with your GitHub organization name — and approve the 🔒 prompt:",
              say("Set reviewers.github-team in governance/write-policy.yaml to @<your-org>/os-admins and regenerate .github/CODEOWNERS"),
              callout("expected", "Claude confirms both files changed. When it finishes the response, auto-sync saves them on your branch, next to the customization changes.")),
          ])),
        platform("azure",
          p("Nothing to do on Azure Repos — the repository admin already chose `OS-Admins` as the required reviewer in the branch policy. Continue with step 3.")),
        h2("Step 3 — Publish the changes for everyone", "z3"),
        p("Gated changes wait on your branch until they are approved. As a Work OS admin you can approve your own — so tell Claude to do the whole thing: open the pull request, approve it as you, and {gh:merge|az:complete} it."),
        steps([
          step("Ask Claude:", platform("github", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and merge it")), platform("azure", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and complete it")),
            callout("expected", "Claude opens one pull request *\"gated: …\"* with everything from {gh:steps 1 and 2|az:step 1}, approves it as you and {gh:merges it — GitHub labels this *merged with bypass*, because authors can't approve their own pull request there; your `os-admins` membership allows the merge|az:completes it — the required-reviewer policy is satisfied by your own approval} — and reports the link.")),
        ]),
        callout("check", "The pull request is {gh:merged|az:completed}. On `main`, `governance/write-policy.yaml` shows `auto-commit: enabled: true`{gh: and `.github/CODEOWNERS` shows `@<your-org>/os-admins` next to every gated path|az:}. From now on auto-sync is on for everyone who pulls."),
        callout("tip", "Prefer to look before it lands? Say *\"propose the gated changes\"* instead — Claude only opens the pull request, and you approve and {gh:merge|az:complete} it yourself in {gh:GitHub|az:Azure Repos}. Work OS users always take this route: their pull requests wait for an admin."),
        h2("Step 4 — Do the first access test", "z4"),
        p("Same two tests every user will do in Stage 3 — you go first, so you know the loop works before inviting the team."),
        steps([
          step("Everyday change:", say("Create a short test meeting summary at product-development/product/meetings/other/summaries/<today's date>-access-test.md and mark it clearly as TEST"),
            callout("check", "Within about a minute the file is on `main`; a pull request *\"context: sync from sync/<your name>\"* merged by itself.")),
          step("Gated change — approve the 🔒 prompt, wait for Claude to finish, then publish:", say("In business-info.md, fill in the company name line"), platform("github", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and merge it")), platform("azure", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and complete it")),
            callout("check", "The {gh:merged|az:completed} pull request *\"gated: …\"* shows {gh:`os-admins` as code owner and *merged with bypass*|az:`OS-Admins` as required reviewer, approved by you}; the change is on `main`.")),
        ]),
        callout("pass", "Both tests landed on `main`, and the gated one needed an admin. Stage 2 is complete — tell the users they can start Stage 3: [Set up your computer](#/setup/computer). When you're ready, continue with the optional [Connect your tools](#/setup/tools) and [Connect your product's code](#/setup/code)."),
      ]},

      { id: "tools", title: "Connect your tools", audience: "Stage 2 · Work OS admin, then each user for their own account", time: "5–20 minutes per tool — optional", blocks: [
        lead("Out of the box, the Work OS works with whatever you paste or drop into it — transcripts, exports, notes. Connecting a tool lets Claude read it live and write back to it, so the same skills run without the copy-and-paste. Optional; connect tools one at a time, whenever you're ready."),
        h2("Which tools are worth connecting", "which"),
        table(["System", "What Claude can do with it", "Skills that use it", "Without it"], [
          ["**Meeting recordings** — Fireflies, Otter, Zoom, Teams, Granola", "Pull transcripts by itself and turn them into summaries, decisions and action items", "`/process-meeting`, `/portfolio-pulse`", "You paste the transcript, or drop the file into `product-development/inbox/`"],
          ["**Task tracker** — Linear, Jira, Asana, monday, ClickUp", "Create tickets from an agreed spec; read status for updates and plans", "`/create-tickets`, `/status-update`, `/weekly-review`, `/daily-plan`", "Claude gives you ready-to-paste tickets; you tell it the status"],
          ["**Team chat** — Slack, Microsoft Teams", "Post digests and drafts; read a thread you point at", "`/slack-message`, `/weekly-review`, `/portfolio-pulse`, `/status-update`", "Claude drafts the message; you paste it"],
          ["**Product analytics** — Amplitude, Mixpanel, PostHog, Pendo", "Query retention, activation and funnels live", "`/retention-analysis`, `/activation-analysis`, `/feature-metrics`, `/experiment-metrics`", "You export the numbers or paste a chart's data"],
          ["**Documents** — Notion, Confluence, Google Drive", "Read source documents when folding context into the Work OS", "`/context-update`, `/user-research-synthesis`, `/prd-draft`", "You paste or attach the document"],
          ["**Design** — Figma", "Read designs and link prototypes", "`/prototype`, `/prototype-feedback`, `/create-tickets`", "You describe or link the design"],
          ["**Customer feedback** — Intercom", "Pull customer requests and conversations", "`/prioritize-requests`", "You paste the pile of requests"],
          ["**Calendar** — Google Calendar, Outlook", "Plan the day around meetings", "`/daily-plan`, `/meeting-agenda`", "You tell Claude your day"],
        ], [2500, 2700, 2500, 2200]),
        callout("tip", "A good first set: **meeting recordings**, your **task tracker**, and **team chat**. They remove the most copy-and-paste."),
        h2("How connecting works", "how"),
        p("Each connection is a small standard connector (an *MCP server*) that lets Claude use the tool with your own login. Two parts: the **Work OS admin** connects a tool once and lets Claude record which skills use it — that record is shared with the team. Then **each person** connects the same tool on their own computer with their own account, so Claude acts as them, not as the admin."),
        callout("note", "Your passwords and tokens never go into the Work OS repository or into chat. Claude keeps them in Claude Code's own settings on your computer."),
        h2("Step 1 — Connect a tool for the team (Work OS admin)", "t1"),
        steps([
          step("Ask Claude — one tool at a time:", say("/connect-mcps connect to Linear")),
          "Follow the conversation. Claude finds the official connector for the tool, sets it up, and asks you to sign in to the tool in your browser when needed. If Claude shows a command to run, ask it to run it for you.",
          step("Claude tests the connection and records which Work OS skills will use the tool. Approve the 🔒 prompt (the record lives in gated files).",
            callout("expected", "Claude reports the connection works and lists the skills it wired — for example \"`/create-tickets` will now create tickets in Linear\". A log is saved in `os-installation/mcp-integration-logs/`.")),
          step("Publish the record for everyone — you're a Work OS admin, so Claude opens the pull request, approves it as you and {gh:merges|az:completes} it:", platform("github", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and merge it")), platform("azure", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and complete it"))),
        ]),
        h2("Step 2 — Connect the same tool for yourself (each user)", "t2"),
        steps([
          step("Ask Claude:", say("/connect-mcps connect to Linear"),
            callout("expected", "Claude sees the tool is already registered for the team, sets up the connection on your computer, and asks you to sign in with your own account. Done in a minute or two.")),
        ]),
        callout("pass", "Ask Claude something the tool answers — *\"what did we decide in yesterday's product sync?\"* (meeting recordings), *\"what's open in this sprint?\"* (task tracker) — and get a live answer instead of a request to paste something."),
      ]},

      { id: "code", title: "Connect your product's code", audience: "Stage 2 · Work OS admin, then each user on their own computer", time: "15 minutes per repository — optional", blocks: [
        lead("With read access to your product's source code, Claude answers product questions from the code itself — how a feature actually works today, what limits apply, whether a change is live — in plain language, with the evidence available on request. Optional. Read-only: Claude never changes the product code from the Work OS."),
        h2("What it gives you", "what"),
        table(["You ask", "Skill", "Without the connection"], [
          ["\"How does the export limit actually work today?\" · \"Is the new pricing live?\" · \"Do we support SSO?\"", "`/code-qa` — answers from the code, concise, no jargon", "Claude says it has no grounded code access and gives you the exact question to ask an engineer"],
          ["\"Draft a first implementation of this job spec\"", "`/code-first-draft` — a first-pass implementation with tests, for engineers to take over", "Claude writes a standalone reference implementation instead"],
          ["\"Is this spec feasible?\" (inside PRD and job-spec work)", "`/job-spec-draft`, `/job-spec-challenge` — a feasibility check grounded in the code", "The check is marked as a to-do for engineering"],
        ], [3800, 3000, 2600]),
        h2("How it works", "how"),
        p("Two parts, like tools. The Work OS keeps a small **registry** of your code repositories — what each one is for and which product areas it covers, in your own words. That is shared. Each person's **computer** holds a read-only copy of the code that Claude may read but never edit — that stays private and is never uploaded to the Work OS."),
        h2("Before you start", "before"),
        checklist([
          "You know which repositories matter to product questions and have their links (skip infrastructure and tooling repositories).",
          "The people who will use it have read access to those repositories — their normal developer access. The {gh:GitHub|az:Azure DevOps} sign-in from [Set up your computer](#/setup/computer) usually covers it.",
        ]),
        h2("Step 1 — Register a repository for the team (Work OS admin)", "k1"),
        steps([
          step("Ask Claude — one repository at a time:", say("/connect-code <paste the repository link>")),
          "Answer in your own words: what the repository is for, and which product areas it covers (the words your team uses — that is how Claude routes a question to the right code). For a very large repository Claude asks which folders matter.",
          step("Approve the 🔒 prompt — the registry is a gated file. Claude then copies the code to your computer (read-only) and grants itself read access there. For a large repository it offers to build a map of the code — say yes.",
            callout("expected", "`product-development/engineering/code-repos.yaml` lists the repository with its purpose and areas. Nothing about your computer or your credentials is written into it.")),
          step("Publish the registry entry for everyone — as a Work OS admin, Claude opens the pull request, approves it as you and {gh:merges|az:completes} it:", platform("github", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and merge it")), platform("azure", say("Publish the gated changes for everyone — I'm a Work OS admin: open the pull request, approve it and complete it"))),
        ]),
        h2("Step 2 — Get access on your own computer (each user)", "k2"),
        steps([
          step("Ask Claude:", say("/connect-code"),
            callout("expected", "Claude finds the repositories the admin registered, copies them to your computer, and grants itself read-only access. It never changes the shared repository in this run.")),
        ]),
        h2("Keeping it fresh", "refresh"),
        p("Ask Claude *\"refresh the code access\"* (`/connect-code --refresh`) now and then — it pulls the latest code and updates the maps. The weekly health check reminds you when the registry goes stale."),
        callout("pass", "Ask *\"/code-qa how does <a feature you know> work today?\"* and get an answer that cites the code — with *\"show the evidence\"* revealing file and line references."),
      ]},

      { id: "troubleshooting", title: "Troubleshooting", audience: "Everyone", time: "", blocks: [
        lead("What you might see, what it means, and what to do. Everything here is reported by Claude at the end of a response — you can always ask *\"what did auto-sync report?\"*"),
        h3("Claude notes \"NO pull request opened … {gh:gh is not logged in|az:az lacks the azure-devops extension}\"", "q1"),
        p("Your {gh:GitHub|az:Azure} sign-in on this computer is missing or expired. Redo [Set up your computer, step 5](#/setup/computer/c5). The note names the branch that was pushed — a Work OS admin can merge it once by hand from the repository page."),
        platform("github",
          h3("An everyday pull request stays \"left OPEN — could not merge yet\"", "q2"),
          p("Either *Allow auto-merge* is off in the repository settings ([Set up the repository, step 4](#/setup/repository/s4)) or a required check is still running. Auto-sync retries after every response.")),
        h3("A gated pull request merged without admin approval", "q3"),
        platform("github", p("One of: `.github/CODEOWNERS` still has the placeholder `@[org]/os-admins` ([Customize the Work OS, step 2](#/setup/customize/z2)); the `os-admins` team lacks Write access; *Require review from Code Owners* is not ticked in the ruleset.")),
        platform("azure", p("Either the reviewer policy is *Optional* instead of *Required*, or its path filter is outdated. The Work OS admin can ask Claude for the current line (*\"print the Azure path filter for the gated files\"*) and the repository admin pastes it into the policy.")),
        h3("\"/auto-sync status\" says OFF for a teammate", "q4"),
        p("The switch hasn't reached `main` yet, or the teammate's copy is behind. The Work OS admin checks that the setup pull request was merged ([Customize the Work OS, step 3](#/setup/customize/z3)); the teammate asks Claude *\"pull the latest changes\"* and checks again."),
        h3("\"REBASE CONFLICT: sync/<you> does not rebase onto origin/main\"", "q5"),
        p("Someone changed the same file. Ask Claude: *\"resolve the rebase conflict on my branch, keeping both changes where possible\"* — it walks you through it. Auto-sync resumes at the next response."),
        h3("Claude says the push to main was rejected", "q6"),
        p("Expected for Work OS users — `main` is protected; auto-sync uses pull requests instead. If a Work OS admin sees it, check they are in the {gh:`os-admins` team|az:`OS-Admins` group}."),
        h3("How do we change which files are gated?", "q7"),
        p("The Work OS admin edits the list in `governance/write-policy.yaml` (it is gated itself, so the change goes through *\"propose the gated changes\"*). {gh:`.github/CODEOWNERS` regenerates by itself.|az:The repository admin pastes the new path filter into the branch policy — the pull request description contains the line.}"),
        h3("Can I use the Work OS without auto-sync?", "q8"),
        p("Yes, on your own — but your work stays on your computer until someone commits it by hand, and the team won't see it. Auto-sync is what makes it teamwork."),
        h3("Can two people work at the same time?", "q9"),
        p("Yes. Each person has their own branch; changes to different files never conflict. Changes to the same file are combined automatically when possible — see the rebase-conflict entry above for the rare case they aren't."),
      ]},
    ]},
  ],
};

module.exports = doc;
